# Plik konfiguracyjny do automatycznego działania programu PyReport
# Wywołanie: python main.py --config config.yaml

input_dir: test_data
input_file: sprzedaz_produkty.csv
encoding: utf-8

# Automatyczne filtrowanie (opcjonalnie, tu wyłączone)
filters: []

# Automatyczne sortowanie (opcjonalnie)
sort:
  column: "Sprzedaż"
  order: "desc"

# Definicje wykresów do wygenerowania
charts:
  - type: "bar"
    columns: ["Kategoria"]           # Słupkowy: liczba produktów w kategoriach
  - type: "line"
    columns: ["Produkt", "Sprzedaż"] # Liniowy: sprzedaż według produktu
  - type: "pie"
    columns: ["Kategoria"]           # Kołowy: udział każdej kategorii w całości
  - type: "pie_special"
    column: "Produkt"                # Specjalny kołowy: udział wybranych produktów w sprzedaży
    values: ["Laptop", "Telewizor", "Pralka"]  # Podział na te produkty vs reszta

interactive_filter: false
interactive_sort: false
interactive_choose_file: false
interactive_charts: false

charts_dir: charts
reports_dir: reports
