input_dir: test_data
charts_dir: charts
reports_dir: reports

interactive_choose_file: true
interactive_filter: true
interactive_sort: true

charts:
  - type: bar
    columns: ["Produkt"]
  - type: line
    columns: ["Data", "Wartość"]
  - type: bar
    columns: ["Miasto"]